### ISSUE TITLE
Stylistic changes and bugfixes

### ISSUE THREAD

**Issue by hellerve** [brightforme/python-streamlike#2]
Hey,

after reviewing your code for some time and identifying some bugs/weaknesses, I got my hands dirty and reworked the code a bit. It can currently be found in the [experimental](https://github.com/hellerve/python-streamlike/tree/experimental) branch.

The following features are included:
- Largely PEP8 conformant rewrite
- Documented EVERYTHING
- Bugfix in helpers.py (typo in variable name)
- Decoupled exceptions from helpers module
- Decoupled error parsing

Take a look at it and tell me whether you like it. If you don't, I'll just give you the bugfixes. If you do, I will issue a PR.

Cheers

**Comment by mekza** [comment]
Sounds awesome! You can issue a PR.

Thx
